### ISSUE TITLE
!BREAKING CHANGE: API 구조 변경

### ISSUE THREAD

**Issue by 134130** [osamhack2021/Web_Handover_Handover#10]
HTTP request -> Service -> Repository -> 실제 DB 업데이트

**Comment by 134130** [comment]
Entity <-> Service <-> Router 로 최종 구조 변경

**Comment by phjppo0918** [comment]
feature/back/#10 브랜치에 작성했고 푸시 했습니다!
앞으로 파일명, 변수명에 대해서 가이드라인이있었으면 좋겠어요!
그리고, routes/user 와 models/User 같은 경우 파일명이 비슷해서 둘 중 하나는 변경하는게 좋을 것 같아요! router/user에서 user을 userController이나 userRouter로 변경하면 어떨까요??
마지막으로, 

또한 제가 구조 변경을 하면서 함수에 async, await 예약어를 사용했는데 제대로 사용한 것인지는 잘 모르겠네요 ㅠㅠㅠ 한번 검토 부탁드립니다! (실행은 잘 됩니다!)

마지막으로 UserService 맨 마지막 부분에
```
module.exports.findAll = findAll;
module.exports.findById = findById;
module.exports.save = save;
```
이런 식으로 exports를 작성했는데 뭔가 깔끔해 보이지가 않아서요...! 더 좋은 표현법이 있을지 궁금합니다!

**Comment by 134130** [comment]
> 앞으로 파일명, 변수명에 대해서 가이드라인이있었으면 좋겠어요!
> 그리고, routes/user 와 models/User 같은 경우 파일명이 비슷해서 둘 중 하나는 변경하는게 좋을 것 같아요! router/user에서 user을 userController이나 userRouter로 변경하면 어떨까요??

routes 같은 경우에는 `https://HOST/...`를 나타내기 때문에 user.js로 유지하면 될 것 같습니다.
services 하위에서는 `services/userService.js`, models 에서는 `models/userModel.js`양식으로 하겠습니다.

> 이런 식으로 exports를 작성했는데 뭔가 깔끔해 보이지가 않아서요...! 더 좋은 표현법이 있을지 궁금합니다!

다양한 방법이 있습니다.
1. `module.exports = { findAll, findById, save };`
2. `module.exports = {
    findAll: function() { ... },
    findById: function() { ... }
};`

저는 개인적으로 2번이 나은것 같습니다.

**Comment by phjppo0918** [comment]
Entity <-> Service <-> Controller <-> Router 구조 설정
