### ISSUE TITLE
Feat: 로그인 기능 구현

### ISSUE THREAD

**Issue by phjppo0918** [osamhack2021/Web_Handover_Handover#12]
Session방식으로 로그인

**Comment by phjppo0918** [comment]
현재 feature/backend/#12 작성중이고, 해당 코드에 문제가 있어 pull request는 하지 않았습니다! 문제 중 일부는 원인과 해결책을 찾았지만, 개인사정으로 내일 반영하도록 하겠습니다!
1. request.body 의 value가 undefind되어있습니다! 별도의 test 리포에서 모듈의 우선순위를 변경하자 정상작동 되었습니다! 내일 본 프로젝트에 반영할 계획입니다
참조 : https://2dubbing.tistory.com/50
2. password 암호화 시 ERR_CRYPTO_HASH_FINALIZED가 발생합니다! 
![image](https://user-images.githubusercontent.com/55674648/133930673-9b1b4526-33db-4364-949b-cc6ff573f286.png)
다음과 같은 수정안을 작성해서 테스트 해보았고, 정상작동 되었습니다! 이것도 내일 안으로 반영하겠습니다!
```
try {
			shasum = crypto.createHash('sha256');
			params.password = shasum.digest(params.password);
```

3. login 호출 시 시간초과가 되는 현상이 발생하고 있습니다! 내일 원인을 찾아서 수정하겠습니다! 
4. login에 대한 rest api설계에 대해서 같이 고민해야 할 것 같습니다! 지금은 일단 common을 만들어서 관리를 하고 있는데 더 좋은 방안이 무엇일까 한번 상의하면 좋을 것 같습니다
5.
```
try {
			shasum = crypto.createHash('sha256');
			params.password = shasum.digest(params.password);
			const loginUser = await User.serviceNumber(params.serviceNumber);

			if(!loginUser) {
				throw new Error('user not found');
			}
			
			if(loginUser.password !== params.password) {
				throw new Error('Passwords do not match');
			}

			return true;
		}catch(error){
			
		}
```
예외처리 방안에 대해 어떻게 하면 좋을 지 방향을 잡지 못해서 일단은 이렇게 작성했습니다! 어떤 식으로 예외처리를 해야 좋을지 알려주시면 감사하겠습니다!

**Comment by 134130** [comment]
> login에 대한 rest api설계에 대해서 같이 고민해야 할 것 같습니다! 지금은 일단 common을 만들어서 관리를 하고 있는데 더 좋은 방안이 무엇일까 한번 상의하면 좋을 것 같습니다

common을 만들어서 관리를 한다는게 어떤 뜻인지 잘 모르겠습니다. 내일 한 번 상의해보면 될 것 같습니다.

> 5. 예외처리 방안에 대해 어떻게 하면 좋을 지 방향을 잡지 못해서 일단은 이렇게 작성했습니다! 어떤 식으로 예외처리를 해야 좋을지 알려주시면 감사하겠습니다!

Issues #18 에서 error처리에 관한 middleware 추가를 계획 중입니다.
우선 예외처리에 대한 내용은 잠시 보류하면 될 것 같습니다.

**Comment by phjppo0918** [comment]
```
if(loginUser.password !== params.password) {
				throw new Error('Passwords do not match');
			}
``` 
여기서 !==을 !=로 수정하니 테스트리포에서 제대로 로그인되었습니다! 바로 반영 후 푸시하겠습니다

**Comment by 134130** [comment]
!== 로 타입까지 검사하는게 맞는데..
이따 fetch후 한 번 확인 해 보겠습니다!
