### ISSUE TITLE
Fix: Authentication is possible with invalid password

### ISSUE THREAD

**Issue by 134130** [osamhack2021/Web_Handover_Handover#26]

**Comment by phjppo0918** [comment]
![image](https://user-images.githubusercontent.com/55674648/134159827-22849dac-f4c1-468b-8938-5f0bc1d63865.png)
![image](https://user-images.githubusercontent.com/55674648/134159865-3f4e61f6-ea01-4023-a1c6-318ce993b742.png)
비밀번호가 달라도 로그인 되는 버그 수정했습니다! encode 함수를 제가 잘못 작성했더라구요 ㅠㅠ
지금은 Service에서 encode하는 거를 함수로 빼놔서 코드 가독성도 더 좋아진 것 같아요!
암호화에 있어서 보완해야 하는 점은 salting이랑 hash화를 여러번 중첩해서 보안성을 높이면 더 좋을 것 같습니다!
