### ISSUE TITLE
Chore: Update jade dependency

### ISSUE THREAD

**Issue by ntcho** [osamhack2021/Web_Handover_Handover#27]
The following warning occurs on `npm install` for `/backend`. Please check out the latest package [here (latest version is `pug:3.0.2`)](https://www.npmjs.com/package/pug) and update if possible.

```
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
```

**Comment by 134130** [comment]
We don't use `Jade` aka `pug` (Template Module) now.
dependencies in package.json should be updated.
I'll mirror on package.json

`docker-compose down`
`docker-compose up --build`
Try those commands when I resolved this issue.

**Comment by ntcho** [comment]
Thanks! 👍 Please close this issue with the commit when you update the dependencies.
