### ISSUE TITLE
Refactor: 예외처리 구조 리펙터링

### ISSUE THREAD

**Issue by phjppo0918** [osamhack2021/Web_Handover_Handover#40]

**Comment by phjppo0918** [comment]
Error를 크게 BussinessError과 RuntimeError로 분류,
사용자가 정상적인 방법으로 사용 중에 생길 수 있는 에러를 BussinessError
비 정상적인 혹은 예상할 수 없는 방식으로 접근하거나, 서버 내에서 생기는 오류는 RuntimeError
만약 더 세부적인 Exception을 원한다면 BussinessError혹은 RuntimeError에서 상속받아서 사용 가능하도록 구현

**Comment by 134130** [comment]
나중에 추가될 에러들을 생각하면 `AuthError`가 어떤 `Error`를 상속받는지 한 눈에 구별하기 힘듦.
1. Errors폴더에 BussinessErrors폴더를 만들어 관리하거나
2. `BussinessError.js`에서
```
class BussinessError extends Error {
     // ...
}

class AuthError extends BussinessErrror {
    // ...
}

module.exports = { BussinessError, AuthError };
```
`userService.js`에서
```
const { BusinessError, AuthError } = require('.../BussinessError.js');
```

의 방식이 추후 관리하기 편할 듯함.

**Comment by 134130** [comment]
1. 현재 코드에서 `BussinessError`의 `status`가 `400`으로 고정되어있는데, 이는 추후 `controller`에서 `status`를 명확히해서 `response`할 것인지?
2. `DocumentNotFoundError`는 status가 `500`이 아닌 `404`이여야함
3. `app.js`에서 
```
app.use(function(err, req, res, next) { ... });
```
코드를 완전 지워버렸는데, 이렇게 되면 app.js내부에서 자체적으로 발생하는 에러에 대해 클라이언트엑 발송하지 못함.
client는 TimeOut상태에 놓이게 되는데 이는 적절하지 못하다고 생각됨.
