### ISSUE TITLE
Fix: Reroute all request to /index.html

### ISSUE THREAD

**Issue by ntcho** [osamhack2021/Web_Handover_Handover#42]
Other URL except / won't work because it's compiled with webpack to a SPA.

https://stackoverflow.com/questions/17456729/how-to-redirect-to-single-page-web-app-in-express-for-node
https://github.com/alexbeletsky/backbone-express-spa/blob/master/app.js

**Comment by 134130** [comment]
Great! I couldn't access to api route.

**Comment by ntcho** [comment]
@134130 , I meant the frontend routes. The backend API is delivered from `localhost:3000`.

I was planning to fix the `/frontend/app.js`, not routes from `/backend/app.js`. But I will add references if I find a solution for this on this thread. 🤞

**Comment by 134130** [comment]
> @134130 , I meant the frontend routes. The backend API is delivered from `localhost:3000`.
> 
> I was planning to fix the `/frontend/app.js`, not routes from `/backend/app.js`. But I will add references if I find a solution for this on this thread. 🤞

Yep, but when I up dockers with frontend, I can't access backend resources with port 3000.
When up dockers without frontend. I can access my resources.

**Comment by ntcho** [comment]
Will look into it.

**Comment by ntcho** [comment]
Can you elaborate more on the issue where you can't access `backend` resource when you build with `frontend` service container?
On the Codespaces environment, the ports are not like `example.com:port`, but like `example-port.githubpreview.dev`. Therefore `example-80.githubpreview.dev:3000` won't connect to the `backend` container, but `example-3000.githubpreview.dev` will connect instead.

**Comment by ntcho** [comment]
Fixed with https://github.com/osamhack2021/Web_Handover_Handover/commit/b7043df31b8098857524c0bd6391c4d8cc975a24.

**Comment by 134130** [comment]
@ntcho Yeap. I know that codespace's url contains it's port. I'll check again and open Issue if it don't work again.
