### ISSUE TITLE
Chore: Setup default React app

### ISSUE THREAD

**Issue by ntcho** [osamhack2021/Web_Handover_Handover#8]
https://reactjs.org/docs/create-a-new-react-app.html#create-react-app

Also make it executable on GitHub codespaces

**Comment by 134130** [comment]
개발환경 세팅이 완료 되면 docker-compose로 통합하는 것도 좋아보입니다.

**Comment by ntcho** [comment]
관련 자료나 링크 보내주시면 그대로 설정해보겠습니다! 😊

**Comment by 134130** [comment]
https://javaexpert.tistory.com/1013

**Comment by ntcho** [comment]
Resolved with #16.
